# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);

# 教师注册
# introduction is nullable
POST http://{{host}}/account/teacher
Content-Type: application/json

{
  "username": "teacher1",
  "password": "111",
  "grade": "小六",
  "subject": "生物",
  "name": "喵喵喵",
  "birth": "2018-05-01",
  "phone": "123456789",
  "price": 100,
  "introduction": "我可去你x的吧"
}

###
# 学生注册
POST http://{{host}}/account/student
Content-Type: application/json

{
  "username": "student1",
  "password": "111"
}

###
# 教师登录
POST http://{{host}}/token/teacher
Content-Type: application/json

{
  "username": "teacher1",
  "password": "111"
}

###
# 学生登录
POST http://{{host}}/token/student
Content-Type: application/json

{
  "username": "student1",
  "password": "111"
}

###
# 教师详情
GET http://{{host}}/account/teacher
Cookie: SESSION=NjljNzkyZDUtYzNiMy00ZGMwLWEwMDAtZGQ0YjE4NzUxM2I4; Path=/; HttpOnly

###
# 学生详情
GET http://{{host}}/account/student
Cookie: SESSION=MThiNmUyOWEtNTE4ZC00MzE0LThlZGYtZTc3OGIyNTliNjBk; Path=/; HttpOnly

###
# 教师修改密码
PUT http://{{host}}/account/teacher/password
Cookie: SESSION=NjljNzkyZDUtYzNiMy00ZGMwLWEwMDAtZGQ0YjE4NzUxM2I4; Path=/; HttpOnly
Content-Type: application/json

{
  "old": "111",
  "new": "112"
}
###
# 学生修改密码
PUT http://{{host}}/account/student/password
Cookie: SESSION=MThiNmUyOWEtNTE4ZC00MzE0LThlZGYtZTc3OGIyNTliNjBk; Path=/; HttpOnly
Content-Type: application/json

{
  "old": "111",
  "new": "112"
}
###
# 修改教师空闲时间
PUT http://{{host}}/account/teacher/freetime
Cookie: SESSION=YjFiMTkzNTktMDY5YS00NTQ2LWI3OWItZmJiOWUzMDdjZTk1; Path=/; HttpOnly
Content-Type: application/json

{
  "freetime": [
    {
      "start": 10,
      "end": 11
    },
    {
      "start": 11,
      "end": 12
    }
  ]
}
###
# 学生支付订单
POST http://{{host}}/account/student/orders?id=10
Cookie: SESSION=YjFiMTkzNTktMDY5YS00NTQ2LWI3OWItZmJiOWUzMDdjZTk1; Path=/; HttpOnly

###
# 搜索教师，还有其他参数，看Controllers.kt
GET http://{{host}}/teachers?
#    grade=小六&
#    subject=生物&
#    name=AAA&
#    age=19&
#    date=2018-04-30&
#    time=17-18&
#    price=100-200

###
# 教师详情
GET http://{{host}}/teachers/1

###
# 学生预约教师
POST http://{{host}}/teachers/1/reservation
Content-Type: application/json
Cookie: SESSION=MThiNmUyOWEtNTE4ZC00MzE0LThlZGYtZTc3OGIyNTliNjBk; Path=/; HttpOnly

{
  "date": "2018-05-01",
  "time": "11-12"
}


















###
PUT http://{{host}}/account/teacher/freetime
Content-Type: application/json
Cookie: SESSION=YjFiMTkzNTktMDY5YS00NTQ2LWI3OWItZmJiOWUzMDdjZTk1; Path=/; HttpOnly

{
  "freetime": [
    {
      "start": 10,
      "end": 11
    },
    {
      "start": 11,
      "end": 12
    }
  ]
}

###
